version: "3"
services:
  test-langchain-with-latest-deps:
    image: node:18
    environment:
      PUPPETEER_SKIP_DOWNLOAD: "true"
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "true"
      COHERE_API_KEY: ${COHERE_API_KEY}
    working_dir: /app
    volumes:
      - ../langchain:/langchain
      - ./scripts:/scripts
    command: bash /scripts/langchain/test-with-latest-deps.sh
  test-langchain-with-lowest-deps:
    image: node:18
    environment:
      PUPPETEER_SKIP_DOWNLOAD: "true"
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "true"
      COHERE_API_KEY: ${COHERE_API_KEY}
    working_dir: /app
    volumes:
      - ../turbo.json:/turbo.json
      - ../package.json:/package.json
      - ../libs/langchain-standard-tests:/libs/langchain-standard-tests
      - ../langchain:/langchain
      - ./scripts:/scripts
    command: bash /scripts/langchain/test-with-lowest-deps.sh
  
  test-community-with-latest-deps:
    image: node:18
    environment:
      PUPPETEER_SKIP_DOWNLOAD: "true"
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "true"
      COHERE_API_KEY: ${COHERE_API_KEY}
    working_dir: /app
    volumes:
      - ../turbo.json:/turbo.json
      - ../package.json:/package.json
      - ../libs/langchain-standard-tests:/libs/langchain-standard-tests
      - ../libs/langchain-community:/libs/langchain-community
      - ./scripts:/scripts
    command: bash /scripts/with_standard_tests/community/test-with-latest-deps.sh
  test-community-with-lowest-deps:
    image: node:18
    environment:
      PUPPETEER_SKIP_DOWNLOAD: "true"
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "true"
      COHERE_API_KEY: ${COHERE_API_KEY}
    working_dir: /app
    volumes:
      - ../turbo.json:/turbo.json
      - ../package.json:/package.json
      - ../libs/langchain-standard-tests:/libs/langchain-standard-tests
      - ../libs/langchain-community:/libs/langchain-community
      - ./scripts:/scripts
    command: bash /scripts/with_standard_tests/community/test-with-lowest-deps.sh

  test-openai-with-latest-deps:
    image: node:18
    environment:
      PUPPETEER_SKIP_DOWNLOAD: "true"
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "true"
      COHERE_API_KEY: ${COHERE_API_KEY}
    working_dir: /app
    volumes:
      - ../turbo.json:/turbo.json
      - ../package.json:/package.json
      - ../libs/langchain-standard-tests:/libs/langchain-standard-tests
      - ../libs/langchain-openai:/libs/langchain-openai
      - ./scripts:/scripts
    command: bash /scripts/with_standard_tests/openai/test-with-latest-deps.sh
  test-openai-with-lowest-deps:
    image: node:18
    environment:
      PUPPETEER_SKIP_DOWNLOAD: "true"
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "true"
      COHERE_API_KEY: ${COHERE_API_KEY}
    working_dir: /app
    volumes:
      - ../turbo.json:/turbo.json
      - ../package.json:/package.json
      - ../libs/langchain-standard-tests:/libs/langchain-standard-tests
      - ../libs/langchain-openai:/libs/langchain-openai
      - ./scripts:/scripts
    command: bash /scripts/with_standard_tests/openai/test-with-lowest-deps.sh
